name: archetype
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  postgres:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  api:
    image: ghcr.io/archetype-pal/backend:latest
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      SECRET_KEY: secret
      DEBUG: true
      DATABASE_URL: postgresql://postgres:password@postgres:5432/local
      IIIF_HOST: http://localhost:1024
      ALLOWED_HOSTS: localhost
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:8000
      CSRF_TRUSTED_ORIGINS: http://localhost:3000,http://localhost:8000
    command: python manage.py runserver 0.0.0.0:80 --nostatic
    ports:
      - 8000:80
    volumes:
      - ./storage:/src/storage
    depends_on:
      - postgres
  image_server:
    image: daschswiss/sipi
    ports:
      - 1024:1024
    volumes:
      - ./storage/media:/sipi/images
  frontend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/src/frontend
    depends_on:
      - api
    environment:
      REACT_APP_API_URL: http://localhost:8000  # change this to correct env var name
    command: npm start
volumes:
  postgres:
  logs: