export const FILTER_ORDER_MAP: Record<string, string[]> = {
  manuscripts: [
    'image_availability',
    'text_date',
    'date_precision',
    'format',
    'type',
    'repository_city',
    'repository_name',
    'issuer_name',
    'named_beneficiary',
  ],
  images: [
    'text_date',
    'date_precision',
    'locus',
    'type',
    'repository_city',
    'repository_name',
    'features',
    'components',
    'component_features',
  ],
  scribes: [
    'text_date',
    'scriptorium',
  ],
  hands: [
    'text_date',
    'repository_name',
    'repository_city',
    'place',
  ],
  graphs: [
    'character',
    'character_type',
    'allograph',
    'place',
    'repository_name',
    'repository_city',
    'features',
    'components',
    'component_features',
    'positions',
  ],
  texts: [
    'text_date',
    'date_precision',
    'text_type',
    'type',
    'repository_city',
    'repository_name',
    'status',
    'language',
    'places',
    'people',
  ],
  clauses: [
    'type',
    'repository_city',
    'repository_name',
    'text_date',
    'date_precision',
    'text_type',
    'clause_type',
    'status',
  ],
  people: [
    'type',
    'repository_city',
    'repository_name',
    'text_date',
    'date_precision',
    'text_type',
    'person_type',
    'status',
  ],
  places: [
    'type',
    'repository_city',
    'repository_name',
    'text_date',
    'date_precision',
    'text_type',
    'place_type',
    'status',
  ],
}
