export const FILTER_ORDER_MAP: Record<string, string[]> = {
  manuscripts: [
    'image_availability',
    'text_date',
    'date_precision',
    'type',
    'repository_city',
    'repository_name',
    'issuer_name',
    'named_beneficiary',
  ],
  images: [
    'text_date',
    'date_precision',
    'locus',
    'type',
    'repository_city',
    'repository_name',
    'features',
    'components',
    'component_features',
  ],
  graphs: [
    'text_date',
    'character_type',
    'character',
    'allograph',
    'components',
    'features',
    'component_features',
    'positions',
    'repository_name',
    'repository_city',
  ],
}
