export const FILTER_RENDER_MAP: Record<
  string,
  Record<
    string,
    'checkbox' | 'toggle' | 'range' | 'number-select'
  >
> = {
  manuscripts: {
    image_availability: 'toggle',
    text_date: 'range',
    format: 'checkbox',
    type: 'checkbox',
    repository_city: 'checkbox',
    repository_name: 'checkbox',
  },
  images: {
    text_date: 'range',
    features: 'checkbox',
    components: 'checkbox',
    component_features: 'checkbox',
    repository_city: 'checkbox',
    locus: 'checkbox',
    type: 'checkbox',
    repository_name: 'checkbox',
  },
  scribes: {
    text_date: 'range',
    scriptorium: 'checkbox',
  },
  hands: {
    text_date: 'range',
    repository_name: 'checkbox',
    repository_city: 'checkbox',
    place: 'checkbox',
  },
  graphs: {
    features: 'checkbox',
    components: 'checkbox',
    character: 'checkbox',
    component_features: 'checkbox',
    allograph: 'checkbox',
    character_type: 'checkbox',
    repository_city: 'checkbox',
    positions: 'checkbox',
    repository_name: 'checkbox',
    place: 'checkbox',
  },
  texts: {
    text_date: 'range',
    text_type: 'checkbox',
    type: 'checkbox',
    repository_city: 'checkbox',
    repository_name: 'checkbox',
    status: 'checkbox',
    language: 'checkbox',
    places: 'checkbox',
    people: 'checkbox',
  },
  clauses: {
    text_date: 'range',
    clause_type: 'checkbox',
    text_type: 'checkbox',
    type: 'checkbox',
    repository_city: 'checkbox',
    repository_name: 'checkbox',
    status: 'checkbox',
  },
  people: {
    text_date: 'range',
    person_type: 'checkbox',
    text_type: 'checkbox',
    type: 'checkbox',
    repository_city: 'checkbox',
    repository_name: 'checkbox',
    status: 'checkbox',
  },
  places: {
    text_date: 'range',
    place_type: 'checkbox',
    text_type: 'checkbox',
    type: 'checkbox',
    repository_city: 'checkbox',
    repository_name: 'checkbox',
    status: 'checkbox',
  },
}
