export const FILTER_RENDER_MAP: Record<
  string,
  Record<
    string,
    'checkbox' | 'toggle' | 'range' | 'number-select'
  >
> = {
  manuscripts: {
    image_availability: 'toggle',
    text_date: 'range',
    format: 'checkbox',
    type: 'checkbox',
    repository_city: 'checkbox',
    repository_name: 'checkbox',
  },
  images: {
    text_date: 'range',
    features: 'checkbox',
    components: 'checkbox',
    component_features: 'checkbox',
    repository_city: 'checkbox',
    locus: 'checkbox',
    type: 'checkbox',
    repository_name: 'checkbox',
    issuer_type: 'checkbox',
    issuer: 'checkbox',
    named_beneficiary: 'checkbox',
  },
  texts: {
    repository_name: 'checkbox',
    issuer_type: 'checkbox',
    issuer: 'checkbox',
    named_beneficiary: 'checkbox',
    terms: 'number-select',
  },
  graphs: {
    text_date: 'range',
    features:'checkbox',
    components: 'checkbox',
    character: 'checkbox',
    component_features: 'checkbox',
    allograph: 'checkbox',
    character_type: 'checkbox',
    repository_city: 'checkbox',
    positions: 'checkbox',
    repository_name: 'checkbox',
  },
  clauses: {
    document_type: 'checkbox',
    repository_city: 'checkbox',
    repository: 'checkbox',
    text_type: 'toggle',
    text_date_input: 'number-select',
    text_date_slider: 'range',
    date_precision: 'number-select',
    clause_type: 'checkbox',
    annotated: 'toggle',
    issuer_type: 'checkbox',
    issuer: 'checkbox',
    named_beneficiary: 'checkbox',
  },
  places: {
    document_type: 'checkbox',
    repository_city: 'checkbox',
    repository: 'checkbox',
    text_type: 'toggle',
    text_date_input: 'number-select',
    text_date_slider: 'range',
    date_precision: 'number-select',
    clause_type: 'checkbox',
    annotated: 'toggle',
  },
  people: {
    document_type: 'checkbox',
    repository_city: 'checkbox',
    repository: 'checkbox',
    text_type: 'toggle',
    text_date_input: 'number-select',
    text_date_slider: 'range',
    date_precision: 'number-select',
    clause_type: 'checkbox',
    annotated: 'toggle',
  }
}
