export const SEARCH_RESULT_TYPES = [
  'manuscripts',
  'images',
  'scribes',
  'hands',
  'graphs',
  'texts',
  'clauses',
  'people',
  'places',
] as const;
export type ResultType = (typeof SEARCH_RESULT_TYPES)[number];
export type FacetRenderType = 'checkbox' | 'toggle' | 'range' | 'number-select';

export type SearchResultConfig = {
  label: string;
  apiPath: string;
  defaultVisibleColumns: readonly string[];
  filterOrder: readonly string[];
  filterRenderMap: Record<string, FacetRenderType>;
};

export const SEARCH_RESULT_CONFIG = {
  manuscripts: {
    label: 'Manuscripts',
    apiPath: 'item-parts',
    defaultVisibleColumns: [
      'Repository City',
      'Repository',
      'Shelfmark',
      'Catalogue Num.',
      'Text Date',
      'Doc. Type',
      'Images',
    ],
    filterOrder: [
      'image_availability',
      'text_date',
      'format',
      'type',
      'repository_city',
      'repository_name',
    ],
    filterRenderMap: {
      image_availability: 'toggle',
      text_date: 'range',
      format: 'checkbox',
      type: 'checkbox',
      repository_city: 'checkbox',
      repository_name: 'checkbox',
    },
  },
  images: {
    label: 'Images',
    apiPath: 'item-images',
    defaultVisibleColumns: [
      'Repository City',
      'Repository',
      'Shelfmark',
      'Category Number',
      'Doc. Type',
      'Thumbnail',
      'Ann.',
    ],
    filterOrder: [
      'text_date',
      'locus',
      'type',
      'repository_city',
      'repository_name',
      'features',
      'components',
      'component_features',
    ],
    filterRenderMap: {
      text_date: 'range',
      features: 'checkbox',
      components: 'checkbox',
      component_features: 'checkbox',
      repository_city: 'checkbox',
      locus: 'checkbox',
      type: 'checkbox',
      repository_name: 'checkbox',
    },
  },
  scribes: {
    label: 'Scribes',
    apiPath: 'scribes',
    defaultVisibleColumns: ['Scribe Name', 'Date', 'Scriptorium'],
    filterOrder: ['text_date', 'scriptorium'],
    filterRenderMap: {
      text_date: 'range',
      scriptorium: 'checkbox',
    },
  },
  hands: {
    label: 'Hands',
    apiPath: 'hands',
    defaultVisibleColumns: [
      'Hand Title',
      'Repository City',
      'Repository',
      'Shelfmark',
      'Place',
      'Date',
      'Catalogue Num.',
    ],
    filterOrder: ['text_date', 'repository_name', 'repository_city', 'place'],
    filterRenderMap: {
      text_date: 'range',
      repository_name: 'checkbox',
      repository_city: 'checkbox',
      place: 'checkbox',
    },
  },
  graphs: {
    label: 'Graphs',
    apiPath: 'graphs',
    defaultVisibleColumns: [
      'Repository City',
      'Repository',
      'Shelfmark',
      'Document Date',
      'Allograph',
      'Thumbnail',
    ],
    filterOrder: [
      'character',
      'character_type',
      'allograph',
      'place',
      'repository_name',
      'repository_city',
      'features',
      'components',
      'component_features',
      'positions',
    ],
    filterRenderMap: {
      features: 'checkbox',
      components: 'checkbox',
      character: 'checkbox',
      component_features: 'checkbox',
      allograph: 'checkbox',
      character_type: 'checkbox',
      repository_city: 'checkbox',
      positions: 'checkbox',
      repository_name: 'checkbox',
      place: 'checkbox',
    },
  },
  texts: {
    label: 'Texts',
    apiPath: 'texts',
    defaultVisibleColumns: ['Repository City', 'Repository', 'Shelfmark', 'Text Type', 'MS Date'],
    filterOrder: [
      'text_date',
      'text_type',
      'type',
      'repository_city',
      'repository_name',
      'status',
      'language',
      'places',
      'people',
    ],
    filterRenderMap: {
      text_date: 'range',
      text_type: 'checkbox',
      type: 'checkbox',
      repository_city: 'checkbox',
      repository_name: 'checkbox',
      status: 'checkbox',
      language: 'checkbox',
      places: 'checkbox',
      people: 'checkbox',
    },
  },
  clauses: {
    label: 'Clauses',
    apiPath: 'clauses',
    defaultVisibleColumns: [
      'Cat. Num.',
      'Document Type',
      'Repository City',
      'Repository',
      'Shelfmark',
      'Text Date',
      'Text Type',
      'Clause Type',
    ],
    filterOrder: [
      'type',
      'repository_city',
      'repository_name',
      'text_date',
      'text_type',
      'clause_type',
      'status',
    ],
    filterRenderMap: {
      text_date: 'range',
      clause_type: 'checkbox',
      text_type: 'checkbox',
      type: 'checkbox',
      repository_city: 'checkbox',
      repository_name: 'checkbox',
      status: 'checkbox',
    },
  },
  people: {
    label: 'People',
    apiPath: 'people',
    defaultVisibleColumns: [
      'Cat. Num.',
      'Document Type',
      'Repository City',
      'Repository',
      'Shelfmark',
      'Text Date',
      'Text Type',
      'Category',
    ],
    filterOrder: [
      'type',
      'repository_city',
      'repository_name',
      'text_date',
      'text_type',
      'person_type',
      'status',
    ],
    filterRenderMap: {
      text_date: 'range',
      person_type: 'checkbox',
      text_type: 'checkbox',
      type: 'checkbox',
      repository_city: 'checkbox',
      repository_name: 'checkbox',
      status: 'checkbox',
    },
  },
  places: {
    label: 'Places',
    apiPath: 'places',
    defaultVisibleColumns: [
      'Cat. Num.',
      'Document Type',
      'Repository City',
      'Repository',
      'Shelfmark',
      'Text Date',
      'Text Type',
      'Clause Type',
    ],
    filterOrder: [
      'type',
      'repository_city',
      'repository_name',
      'text_date',
      'text_type',
      'place_type',
      'status',
    ],
    filterRenderMap: {
      text_date: 'range',
      place_type: 'checkbox',
      text_type: 'checkbox',
      type: 'checkbox',
      repository_city: 'checkbox',
      repository_name: 'checkbox',
      status: 'checkbox',
    },
  },
} as const satisfies Record<ResultType, SearchResultConfig>;

export const resultTypeItems = SEARCH_RESULT_TYPES.map((value) => ({
  label: SEARCH_RESULT_CONFIG[value].label,
  value,
})) as { label: string; value: ResultType }[];
